export const STORE_TOKEN = 'STORE_TOKEN';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_LOGGED_USER_SUCCESS = 'GET_LOGGED_USER_SUCCESS';
export const GET_LOGGED_USER_FAILURE = 'GET_LOGGED_USER_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
