export const SET_RATING = 'SET_RATING';
export const ADD_REVIEW = 'ADD_COMPANY_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_COMPANY_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_COMPANY_REVIEW_FAILURE';
export const REVIEW_EXISTS = 'REVIEW_EXISTS';
export const REVIEW_EXISTS_SUCCESS = 'REVIEW_EXISTS_SUCCESS';
export const REVIEW_EXISTS_FAILURE = 'REVIEW_EXISTS_FAILURE';
