export const ADD_REVIEW = 'ADD_COMPANY_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_COMPANY_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_COMPANY_REVIEW_FAILURE';
export const SET_HAS_REVIEWED = 'SET_HAS_REVIEWED';
